# Generated by Django 4.2.7 on 2023-12-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BidBazaar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
                ('category', models.TextField()),
                ('base_prize', models.IntegerField()),
                ('incr_prize', models.IntegerField()),
                ('start_auc', models.DateTimeField()),
                ('end_auc', models.DateTimeField()),
            ],
        ),
    ]
