# Generated by Django 4.2.7 on 2023-12-05 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BidBazaar', '0002_listings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
