# Generated by Django 4.2.7 on 2023-12-05 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BidBazaar', '0003_rename_users_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
