# Generated by Django 4.2.7 on 2024-04-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BidBazaar', '0006_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('desc', models.TextField(default='', max_length=1500)),
                ('img', models.ImageField(upload_to='pictures')),
                ('category', models.CharField(choices=[('APR', 'Apartments'), ('CAR', 'Cars'), ('ELE', 'Electronics'), ('FUR', 'Furniture'), ('FAS', 'Fashion'), ('OTH', 'Others')], max_length=3)),
                ('base_prize', models.IntegerField()),
                ('incr_prize', models.IntegerField()),
                ('start_auc', models.DateTimeField()),
                ('end_auc', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Listings',
        ),
    ]
