# Generated by Django 4.2.7 on 2024-05-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BidBazaar', '0007_listing_delete_listings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='id',
            new_name='list_id',
        ),
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=models.ImageField(upload_to='pictures/'),
        ),
    ]
