# Generated by Django 4.2.7 on 2024-05-12 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BidBazaar', '0008_rename_id_listing_list_id_alter_listing_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='latest_bid_prize',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='no_of_bids',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('bid_id', models.AutoField(primary_key=True, serialize=False)),
                ('bid_amt', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('auction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BidBazaar.listing')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
