# Generated by Django 4.2.7 on 2024-05-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BidBazaar', '0009_listing_latest_bid_prize_listing_no_of_bids_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='auc_status',
            field=models.CharField(choices=[('UP', 'Upcoming'), ('AC', 'Active'), ('PA', 'Past'), ('WI', 'Withdrawn')], default='PA', max_length=2),
        ),
    ]
